# docs: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/workflows
      - /.github/actions/* # Not working until resolved: https://github.com/dependabot/dependabot-core/issues/6345
      - /.github/actions/setup
    schedule:
      interval: daily
    groups:
      minors:
        update-types:
          - 'minor'
          - 'patch'
      major:
        update-types:
          - 'major'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      minors:
        update-types:
          - 'minor'
          - 'patch'
      major:
        update-types:
          - 'major'
